// Authentication
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FROM_STORAGE = 'LOGIN_FROM_STORAGE'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
