// Authentication
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGIN_TOKEN_REQUEST = 'LOGIN_TOKEN_REQUEST'
export const LOGIN_TOKEN_SUCCESS = 'LOGIN_TOKEN_SUCCESS'
export const LOGIN_TOKEN_FAILURE = 'LOGIN_TOKEN_FAILURE'
// Set favorites (user model)
export const SET_FAVORITE_REQUEST = 'SET_FAVORITE_REQUEST'
export const SET_FAVORITE_FAILURE = 'SET_FAVORITE_FAILURE'
export const SET_FAVORITE_SUCCESS = 'SET_FAVORITE_SUCCESS'
